# Generated by Django 4.2.5 on 2023-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activity",
            field=models.CharField(
                choices=[
                    ("lowest", "비활동적"),
                    ("low", "저활동적"),
                    ("middle", "활동적"),
                    ("high", "매우 활동적"),
                ],
                default="lowest",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "남"), ("female", "여")], max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
