# Generated by Django 4.2.5 on 2023-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activity",
            field=models.CharField(
                choices=[
                    ("lowest", "비활동적"),
                    ("low", "저활동적"),
                    ("middle", "활동적"),
                    ("high", "매우 활동적"),
                ],
                default="lowest",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.PositiveIntegerField(default=170),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.PositiveIntegerField(default=170),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "남"), ("female", "여")], max_length=30
            ),
        ),
    ]
