# Generated by Django 4.2.5 on 2023-10-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_activity_alter_user_age_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=150, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
