# Generated by Django 4.2.5 on 2023-09-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_activity_user_age_user_height_user_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
