# Generated by Django 4.2.5 on 2023-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0003_selecteddiet_food_gram_alter_dietlist_selected_diet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietlist",
            name="selected_diet",
            field=models.ManyToManyField(
                null=True, related_name="diets", to="diets.selecteddiet"
            ),
        ),
    ]
