# Generated by Django 4.2.5 on 2023-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0003_dietlist_delete_diet"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectedDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("food_name", models.CharField(max_length=250)),
                ("food_calorie", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="dietlist",
            name="food_calorie",
        ),
        migrations.RemoveField(
            model_name="dietlist",
            name="food_name",
        ),
    ]
