# Generated by Django 4.2.5 on 2023-09-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0004_selecteddiet_remove_dietlist_food_calorie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietlist",
            name="selected_diet",
            field=models.ManyToManyField(to="diets.selecteddiet"),
        ),
    ]
