# Generated by Django 4.2.5 on 2023-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0007_alter_dietlist_meal_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietlist",
            name="meal_calorie",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dietlist",
            name="meal_category",
            field=models.CharField(
                choices=[
                    ("breakfast", "아침"),
                    ("lunch", "점심"),
                    ("dinner", "저녁"),
                    ("snack", "간식"),
                    ("night_snack", "야식"),
                    ("drink", "음료"),
                ],
                max_length=30,
            ),
        ),
    ]
