# Generated by Django 4.2.5 on 2023-10-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0008_alter_dietlist_meal_calorie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selecteddiet",
            name="food_calorie",
            field=models.FloatField(),
        ),
    ]
